services:
  
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - ./data/ny_taxi_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_DB=${PG_DATABASE} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5433:5432"
    networks:
      - pg-network
    restart: always
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    volumes:
      - ./data/pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    networks:
      - pg-network
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    

  # elt_app:
  #   build: .
networks:
  pg-network:

volumes:
  - data/ny_taxi_postgres_data:
  - data/pgadmin_data: