dbt_pipelines:
  outputs:

    dev:
      type: postgres
      threads: 200
      host: localhost
      port: 5432
      user: root
      pass: root
      dbname: ny_taxi
      schema: dev

    prod:
      type: postgres
      threads: 200
      host: localhost
      port: 5432
      user: postgres
      pass: postgrespw
      dbname: ny_taxi
      schema: prod

  target: dev