dbt_local:
  target: dev
  
  outputs:
    dev:

      type: postgres
      threads: 200
      host: localhost
      port: 5432
      user: postgres
      pass: postgrespw
      dbname: nyc_taxi
      schema: dev

    prod:
      type: postgres
      threads: 200
      host: localhost
      port: 5432
      user: postgres
      pass: postgrespw
      dbname: nyc_taxi
      schema: public